"""add unique constraint to farm name

Revision ID: 492154bd7664
Revises: a2b8f3bb7732
Create Date: 2026-08-03 11:24:08.877067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492154bd7664'
down_revision: Union[str, Sequence[str], None] = 'a2b8f3bb7732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'farms', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farms', type_='unique')
    # ### end Alembic commands ###
