"""add_season_id_to_dealer_payments

Revision ID: 4f38daaefa92
Revises: a633117a6d8c
Create Date: 2026-09-14 21:57:35.421829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f38daaefa92'
down_revision: Union[str, Sequence[str], None] = 'a633117a6d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealer_payments', sa.Column('season_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dealer_payments_season_id'), 'dealer_payments', ['season_id'], unique=False)
    op.create_foreign_key(None, 'dealer_payments', 'seasons', ['season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dealer_payments', type_='foreignkey')
    op.drop_index(op.f('ix_dealer_payments_season_id'), table_name='dealer_payments')
    op.drop_column('dealer_payments', 'season_id')
    # ### end Alembic commands ###
