"""changes in numeric fields from 5 to 10

Revision ID: 64dd96a8ef86
Revises: db130c2714ea
Create Date: 2026-08-05 21:49:32.393598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64dd96a8ef86'
down_revision: Union[str, Sequence[str], None] = 'db130c2714ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dispatch_items', 'total_weight_kg',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('dispatch_items', 'total_amount',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('dispatch_settlements', 'loss_amount',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('season_box_costs', 'total_amount',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('season_box_costs', 'total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('dispatch_settlements', 'loss_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('dispatch_items', 'total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('dispatch_items', 'total_weight_kg',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
