"""create remaining tables

Revision ID: a80c49c1ef88
Revises: 64dd96a8ef86
Create Date: 2026-08-05 21:53:19.938228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80c49c1ef88'
down_revision: Union[str, Sequence[str], None] = '64dd96a8ef86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dealers', 'commission_value',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('dispatch_items', 'box_quantity',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('dispatch_items', 'price_per_box',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('dispatch_items', 'total_weight_kg',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('free_dispatch_items', 'box_quantity',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('season_box_costs', 'total_boxes',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('season_box_costs', 'price_per_box',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('season_partners', 'partnership_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('season_partners', 'partnership_percentage',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('season_box_costs', 'price_per_box',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('season_box_costs', 'total_boxes',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('free_dispatch_items', 'box_quantity',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('dispatch_items', 'total_weight_kg',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('dispatch_items', 'price_per_box',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('dispatch_items', 'box_quantity',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('dealers', 'commission_value',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
