"""add season in dispatch table as null value

Revision ID: bbbf99daf3e1
Revises: a80c49c1ef88
Create Date: 2026-08-19 20:25:13.101504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbbf99daf3e1'
down_revision: Union[str, Sequence[str], None] = 'a80c49c1ef88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatches', sa.Column('season_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dispatches_season_id'), 'dispatches', ['season_id'], unique=False)
    op.create_foreign_key(None, 'dispatches', 'seasons', ['season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dispatches', type_='foreignkey')
    op.drop_index(op.f('ix_dispatches_season_id'), table_name='dispatches')
    op.drop_column('dispatches', 'season_id')
    # ### end Alembic commands ###
