"""add image to partner_settlements

Revision ID: c8600510a0cb
Revises: 3174bf3a1f35
Create Date: 2026-09-06 22:54:05.089828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8600510a0cb'
down_revision: Union[str, Sequence[str], None] = '3174bf3a1f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_settlements', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_settlements', 'image')
    # ### end Alembic commands ###
