"""add season partner level permission at user level

Revision ID: da97aeb43017
Revises: a59101855a00
Create Date: 2026-09-28 16:54:27.949841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da97aeb43017'
down_revision: Union[str, Sequence[str], None] = 'a59101855a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('season_partners_user_id_fkey'), 'season_partners', type_='foreignkey')
    op.create_foreign_key(None, 'season_partners', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'season_partners', type_='foreignkey')
    op.create_foreign_key(op.f('season_partners_user_id_fkey'), 'season_partners', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
