"""create remaining tables

Revision ID: db130c2714ea
Revises: a4aa475b9b63
Create Date: 2026-08-05 19:34:13.155166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db130c2714ea'
down_revision: Union[str, Sequence[str], None] = 'a4aa475b9b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('seasons',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_seasons_id'), 'seasons', ['id'], unique=False)
    op.create_table('dealer_payments',
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_mode', sa.String(length=100), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('received_by', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_payments_created_by'), 'dealer_payments', ['created_by'], unique=False)
    op.create_index(op.f('ix_dealer_payments_dealer_id'), 'dealer_payments', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_dealer_payments_id'), 'dealer_payments', ['id'], unique=False)
    op.create_table('dispatches',
    sa.Column('dispatch_no', sa.String(length=100), nullable=False),
    sa.Column('dispatch_date', sa.Date(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_no', sa.String(length=20), nullable=True),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('transport_name', sa.String(length=55), nullable=True),
    sa.Column('transport_charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_boxes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispatch_no')
    )
    op.create_index(op.f('ix_dispatches_created_by'), 'dispatches', ['created_by'], unique=False)
    op.create_index(op.f('ix_dispatches_dealer_id'), 'dispatches', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_dispatches_id'), 'dispatches', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=True),
    sa.Column('expense_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('paid_to', sa.String(length=100), nullable=False),
    sa.Column('payment_mode', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_created_by'), 'expenses', ['created_by'], unique=False)
    op.create_index(op.f('ix_expenses_farm_id'), 'expenses', ['farm_id'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_season_id'), 'expenses', ['season_id'], unique=False)
    op.create_table('season_box_costs',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('box_size_kg', sa.String(length=20), nullable=True),
    sa.Column('total_boxes', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('price_per_box', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_box_costs_created_by'), 'season_box_costs', ['created_by'], unique=False)
    op.create_index(op.f('ix_season_box_costs_farm_id'), 'season_box_costs', ['farm_id'], unique=False)
    op.create_index(op.f('ix_season_box_costs_id'), 'season_box_costs', ['id'], unique=False)
    op.create_index(op.f('ix_season_box_costs_season_id'), 'season_box_costs', ['season_id'], unique=False)
    op.create_table('season_partners',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('partner_name', sa.String(length=100), nullable=True),
    sa.Column('partnership_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('agreement_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_partners_farm_id'), 'season_partners', ['farm_id'], unique=False)
    op.create_index(op.f('ix_season_partners_id'), 'season_partners', ['id'], unique=False)
    op.create_index(op.f('ix_season_partners_season_id'), 'season_partners', ['season_id'], unique=False)
    op.create_table('dispatch_items',
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('variety', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('box_size_kg', sa.String(length=20), nullable=True),
    sa.Column('box_quantity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('price_per_box', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_items_dispatch_id'), 'dispatch_items', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_dispatch_items_farm_id'), 'dispatch_items', ['farm_id'], unique=False)
    op.create_index(op.f('ix_dispatch_items_id'), 'dispatch_items', ['id'], unique=False)
    op.create_index(op.f('ix_dispatch_items_product_id'), 'dispatch_items', ['product_id'], unique=False)
    op.create_table('dispatch_settlements',
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('loss_amount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('loss_remarks', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_settlements_dispatch_id'), 'dispatch_settlements', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_dispatch_settlements_id'), 'dispatch_settlements', ['id'], unique=False)
    op.create_table('partner_settlements',
    sa.Column('season_partner_id', sa.Integer(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_expenses', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('partner_percentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('partner_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_mode', sa.String(length=100), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_partner_id'], ['season_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_settlements_created_by'), 'partner_settlements', ['created_by'], unique=False)
    op.create_index(op.f('ix_partner_settlements_id'), 'partner_settlements', ['id'], unique=False)
    op.create_index(op.f('ix_partner_settlements_season_partner_id'), 'partner_settlements', ['season_partner_id'], unique=False)
    op.create_table('free_dispatch_items',
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_item_id', sa.Integer(), nullable=False),
    sa.Column('distribution_date', sa.Date(), nullable=False),
    sa.Column('box_quantity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.ForeignKeyConstraint(['dispatch_item_id'], ['dispatch_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_free_dispatch_items_dispatch_id'), 'free_dispatch_items', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_free_dispatch_items_dispatch_item_id'), 'free_dispatch_items', ['dispatch_item_id'], unique=False)
    op.create_index(op.f('ix_free_dispatch_items_id'), 'free_dispatch_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_free_dispatch_items_id'), table_name='free_dispatch_items')
    op.drop_index(op.f('ix_free_dispatch_items_dispatch_item_id'), table_name='free_dispatch_items')
    op.drop_index(op.f('ix_free_dispatch_items_dispatch_id'), table_name='free_dispatch_items')
    op.drop_table('free_dispatch_items')
    op.drop_index(op.f('ix_partner_settlements_season_partner_id'), table_name='partner_settlements')
    op.drop_index(op.f('ix_partner_settlements_id'), table_name='partner_settlements')
    op.drop_index(op.f('ix_partner_settlements_created_by'), table_name='partner_settlements')
    op.drop_table('partner_settlements')
    op.drop_index(op.f('ix_dispatch_settlements_id'), table_name='dispatch_settlements')
    op.drop_index(op.f('ix_dispatch_settlements_dispatch_id'), table_name='dispatch_settlements')
    op.drop_table('dispatch_settlements')
    op.drop_index(op.f('ix_dispatch_items_product_id'), table_name='dispatch_items')
    op.drop_index(op.f('ix_dispatch_items_id'), table_name='dispatch_items')
    op.drop_index(op.f('ix_dispatch_items_farm_id'), table_name='dispatch_items')
    op.drop_index(op.f('ix_dispatch_items_dispatch_id'), table_name='dispatch_items')
    op.drop_table('dispatch_items')
    op.drop_index(op.f('ix_season_partners_season_id'), table_name='season_partners')
    op.drop_index(op.f('ix_season_partners_id'), table_name='season_partners')
    op.drop_index(op.f('ix_season_partners_farm_id'), table_name='season_partners')
    op.drop_table('season_partners')
    op.drop_index(op.f('ix_season_box_costs_season_id'), table_name='season_box_costs')
    op.drop_index(op.f('ix_season_box_costs_id'), table_name='season_box_costs')
    op.drop_index(op.f('ix_season_box_costs_farm_id'), table_name='season_box_costs')
    op.drop_index(op.f('ix_season_box_costs_created_by'), table_name='season_box_costs')
    op.drop_table('season_box_costs')
    op.drop_index(op.f('ix_expenses_season_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_farm_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_by'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_dispatches_id'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_dealer_id'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_created_by'), table_name='dispatches')
    op.drop_table('dispatches')
    op.drop_index(op.f('ix_dealer_payments_id'), table_name='dealer_payments')
    op.drop_index(op.f('ix_dealer_payments_dealer_id'), table_name='dealer_payments')
    op.drop_index(op.f('ix_dealer_payments_created_by'), table_name='dealer_payments')
    op.drop_table('dealer_payments')
    op.drop_index(op.f('ix_seasons_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
